version: "3.1"

services:
  pg:
    image: postgres
    restart: always
    volumes:
      - ./:/var/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5050:5432